name: smart_app
description: Easy and simple way to design your application
version: 0.0.1
homepage: https://github.com/worldwidee/smart_app

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  internet_connection_checker: ^0.0.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: