name: smart_app
description: Easy and simple way to design your application
version: 0.1.0
homepage: https://github.com/worldwidee/smart_app

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  internet_connection_checker: ^0.0.1+3
  universal_io: ^2.0.4
  crop_your_image: ^0.7.3
  flutter_advanced_avatar: ^1.1.0
  matrix4_transform: ^2.0.1
  boxicons: ^2.1.3
  liquid_progress_indicator: ^0.4.0
  bubble_tab_indicator: ^0.1.6
  flick_video_player: ^0.5.0
  extended_image: ^6.3.2
  dart_vlc: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
